### ISSUE TITLE
能否支持下ARM架构

### ISSUE THREAD

**Issue by sshuai0** [xiaoxinpro/WolGoWeb#1]
N1 arm架构，DOCKER部署成功，自动停止报错standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by xiaoxinpro** [comment]
可以是可以，但是我手头没有arm设备，没办法测试

**Comment by xiaoxinpro** [comment]
```
docker pull chishin/wol-go-web:dev
docker run -d --net=host --env PORT=端口号 chishin/wol-go-web:dev
```
帮忙测试以下，看看是否可以正常使用，无论如何希望可以给予反馈。

**Comment by SmallDS** [comment]
> ```
> docker pull chishin/wol-go-web:dev
> docker run -d --net=host --env PORT=端口号 chishin/wol-go-web:dev
> ```
> 
> 帮忙测试以下，看看是否可以正常使用，希望可以反馈。

在n1上试了下不行，容器刚运行就立马停止了

**Comment by xiaoxinpro** [comment]
麻烦提供以下你设备的ARM架构的版本信息，另外执行一下 `docker images`  提供一下镜像的信息。

**Comment by SmallDS** [comment]
收到，已经提醒管理员查看邮件

**Comment by xiaoxinpro** [comment]
@SmallDS @sshuai0 

更新了新版本的镜像，用下面的镜像再试一下：

```
docker pull chishin/wol-go-web:dev4
docker run -d --net=host --env PORT=端口号 chishin/wol-go-web:dev4
```

**Comment by SmallDS** [comment]
> @SmallDS @sshuai0
> 
> 更新了新版本的镜像，用下面的镜像再试一下：
> 
> ```
> docker pull chishin/wol-go-web:dev4
> docker run -d --net=host --env PORT=端口号 chishin/wol-go-web:dev4
> ```

我用的是n1 Armbian Linux 5.3.8-amlogic-flippy-11+版本         Docker Version:   20.10.12

下面是chishin/wol-go-web:dev4的日志
root@aml:~# docker logs 5c91a6b4c1981f20cef59484c7a384846725a02d4cc8c2abf38acc34d84b284e 
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by SmallDS** [comment]
> 麻烦提供以下你设备的ARM架构的版本信息，另外执行一下 `docker images` 提供一下镜像的信息。

root@aml:~# docker images
REPOSITORY           TAG       IMAGE ID       CREATED          SIZE
chishin/wol-go-web   dev4      28dcdd69f1dd   16 minutes ago   16.2MB

**Comment by xiaoxinpro** [comment]
@SmallDS @sshuai0 

再试一下

```
docker pull chishin/wol-go-web:dev5
docker run -d --net=host --env PORT=端口号 chishin/wol-go-web:dev5
```

**Comment by SmallDS** [comment]
> docker run -d --net=host --env PORT=端口号 chishin/wol-go-web:dev5

可以的，实测可以用

**Comment by SmallDS** [comment]
收到，已经提醒管理员查看邮件
