### ISSUE TITLE
默认的9090端口被扫描

### ISSUE THREAD

**Issue by sars1105** [xiaoxinpro/WolGoWeb#15]
群晖安装docker部署后，默认9090端口运行，docker日志里面能看见有很多外国ip在扫描，但是群晖系统日志里面什么都没有提醒，麻烦看看有没有什么问题，我已经把端口修改了
![Uploading 微信截图_20230816113915.png…]()
![Uploading 微信截图_20230816113943.png…]()

**Comment by xiaoxinpro** [comment]
图片看不到，Docker容器的端口不会经过群晖系统，是直接映射到9090端口的

**Comment by sars1105** [comment]
[GIN] 2023/08/16 - 03:47:22 | 404 |         345ns | 185.216.140.186 | GET      "/ping.js"
[GIN] 2023/08/16 - 04:41:39 | 200 |      27.035µs |    45.40.56.112 | GET      "/"
[GIN] 2023/08/16 - 04:41:59 | 404 |         726ns |    45.40.56.112 | GET      "/favicon.ico"
[GIN] 2023/08/16 - 04:42:00 | 404 |         509ns |    45.40.56.112 | GET      "/robots.txt"
[GIN] 2023/08/16 - 04:42:01 | 404 |         379ns |    45.40.56.112 | GET      "/sitemap.xml"
[GIN] 2023/08/16 - 05:58:41 | 404 |         375ns | 162.142.125.216 | GET      "/api/v1/targets"
[GIN] 2023/08/16 - 05:58:41 | 404 |         734ns | 162.142.125.216 | GET      "/api/v1/targets"
[GIN] 2023/08/16 - 05:58:42 | 404 |         336ns | 162.142.125.216 | GET      "/api/v1/label/version/values"
[GIN] 2023/08/16 - 05:58:42 | 404 |         730ns | 162.142.125.216 | GET      "/api/v1/label/version/values"
[GIN] 2023/08/16 - 05:58:42 | 404 |         720ns | 162.142.125.216 | GET      "/api/v1/label/goversion/values"
[GIN] 2023/08/16 - 05:58:42 | 404 |         482ns | 162.142.125.216 | GET      "/api/v1/label/goversion/values"
[GIN] 2023/08/16 - 05:58:42 | 404 |         347ns | 162.142.125.216 | GET      "/api/v1/query?query=prometheus_build_info"
[GIN] 2023/08/16 - 05:58:43 | 404 |         402ns | 162.142.125.216 | GET      "/api/v1/query?query=prometheus_build_info"
[GIN] 2023/08/16 - 05:58:43 | 404 |       1.014µs | 162.142.125.216 | GET      "/api/v1/labels"
[GIN] 2023/08/16 - 05:58:43 | 404 |         524ns | 162.142.125.216 | GET      "/api/v1/labels"
[GIN] 2023/08/16 - 05:58:43 | 404 |         941ns | 162.142.125.216 | GET      "/api/v1/label/__name__/values"
[GIN] 2023/08/16 - 05:58:43 | 404 |         481ns | 162.142.125.216 | GET      "/api/v1/label/__name__/values"
[GIN] 2023/08/16 - 05:58:44 | 404 |         920ns | 162.142.125.216 | GET      "/api/v1/status/config"
[GIN] 2023/08/16 - 05:58:47 | 200 |      29.306µs | 162.142.125.216 | GET      "/"
[GIN] 2023/08/16 - 05:58:47 | 200 |      28.416µs | 162.142.125.216 | GET      "/"
[GIN] 2023/08/16 - 05:58:48 | 404 |         519ns | 162.142.125.216 | PRI      "*"

**Comment by sars1105** [comment]
[GIN] 2023/08/16 - 05:58:48 | 404 |         597ns | 162.142.125.216 | GET      "/favicon.ico"
[GIN] 2023/08/16 - 06:31:01 | 404 |         636ns |   167.94.145.57 | GET      "/api/v1/targets"
[GIN] 2023/08/16 - 06:31:01 | 404 |         516ns |   167.94.145.57 | GET      "/api/v1/targets"
[GIN] 2023/08/16 - 06:31:01 | 404 |         518ns |   167.94.145.57 | GET      "/api/v1/label/version/values"
[GIN] 2023/08/16 - 06:31:01 | 404 |         426ns |   167.94.145.57 | GET      "/api/v1/label/version/values"
[GIN] 2023/08/16 - 06:31:02 | 404 |         568ns |   167.94.145.57 | GET      "/api/v1/label/goversion/values"
[GIN] 2023/08/16 - 06:31:02 | 404 |         761ns |   167.94.145.57 | GET      "/api/v1/label/goversion/values"
[GIN] 2023/08/16 - 06:31:02 | 404 |         544ns |   167.94.145.57 | GET      "/api/v1/query?query=prometheus_build_info"
[GIN] 2023/08/16 - 06:31:02 | 404 |         436ns |   167.94.145.57 | GET      "/api/v1/query?query=prometheus_build_info"
[GIN] 2023/08/16 - 06:31:03 | 404 |         394ns |   167.94.145.57 | GET      "/api/v1/labels"
[GIN] 2023/08/16 - 06:31:03 | 404 |         793ns |   167.94.145.57 | GET      "/api/v1/labels"
[GIN] 2023/08/16 - 06:31:03 | 404 |         544ns |   167.94.145.57 | GET      "/api/v1/label/__name__/values"
[GIN] 2023/08/16 - 06:31:03 | 404 |         438ns |   167.94.145.57 | GET      "/api/v1/label/__name__/values"
[GIN] 2023/08/16 - 06:31:03 | 404 |         557ns |   167.94.145.57 | GET      "/api/v1/status/config"
[GIN] 2023/08/16 - 06:31:07 | 200 |      22.181µs |   167.94.145.57 | GET      "/"
[GIN] 2023/08/16 - 06:31:07 | 200 |      24.269µs |   167.94.145.57 | GET      "/"
[GIN] 2023/08/16 - 06:31:08 | 404 |         348ns |   167.94.145.57 | PRI      "*"
[GIN] 2023/08/16 - 06:31:08 | 404 |         341ns |   167.94.145.57 | GET      "/favicon.ico"

**Comment by sars1105** [comment]
[GIN] 2023/08/14 - 14:52:40 | 404 |         328ns | 185.216.140.186 | GET      "/ping.js"
[GIN] 2023/08/14 - 14:56:16 | 404 |         344ns |  185.224.128.17 | CONNECT  ""
[GIN] 2023/08/14 - 17:36:13 | 200 |      16.702µs |  198.199.98.133 | GET      "/"
[GIN] 2023/08/14 - 19:20:41 | 404 |         431ns |   59.36.132.222 | CONNECT  ""
[GIN] 2023/08/14 - 19:20:41 | 200 |       16.78µs |   59.36.132.222 | GET      "/"
[GIN] 2023/08/14 - 20:35:47 | 404 |         632ns |   59.36.132.222 | CONNECT  ""
[GIN] 2023/08/14 - 20:35:47 | 200 |      24.147µs |   59.36.132.222 | GET      "/"
[GIN] 2023/08/14 - 21:42:41 | 200 |       25.42µs |  182.92.218.138 | GET      "/"
[GIN] 2023/08/14 - 23:13:07 | 404 |         406ns | 185.216.140.186 | GET      "/ping.js"

**Comment by sars1105** [comment]
麻烦你看看，有没有安全问题，谢谢

**Comment by xiaoxinpro** [comment]
> 麻烦你看看，有没有安全问题，谢谢

只是正常的访问请求，没有安全问题。

**Comment by sars1105** [comment]
> > 麻烦你看看，有没有安全问题，谢谢
> 
> 只是正常的访问请求，没有安全问题。

不是国外的IP在扫描这个端口吗？如果不是，那我就放心了，我已经更改了默认端口，我再观察看看，谢谢！

**Comment by sars1105** [comment]
> > > 麻烦你看看，有没有安全问题，谢谢
> > 
> > 
> > 只是正常的访问请求，没有安全问题。
> 
> 不是国外的IP在扫描这个端口吗？如果不是，那我就放心了，我已经更改了默认端口，我再观察看看，谢谢！
按说，只有我在发出唤醒请求的时候，才会有记录，这些记录来访问，是要干嘛。。。

**Comment by xiaoxinpro** [comment]
只要有访问就会被记录，你多虑了，放着不管就行。

**Comment by sars1105** [comment]
> 

好的好的，谢谢！
