### ISSUE TITLE
如何关闭默认显示的页面，在中国，这违反了法律，会被认为是开启了web服务

### ISSUE THREAD

**Issue by ddkk3000** [xiaoxinpro/WolGoWeb#16]
即下面的页面如何修改或者关闭，我是通过群晖docker布置的。

> WOL唤醒工具

API: 192.168.1.202:9090/wol

Params:
  mac  : 需要唤醒的MAC地址（必须）,
  ip   : 指定IP地址（默认：255.255.255.255）,
  port : 唤醒端口（默认：9）,
  time : 请求时间戳（配合授权验证使用）,
  token: 授权Token = MD5(key + mac + time)（必须存在key的情况下才有效，否则忽略。）,

Version: 0.0.4

我只在目录下看到了完整的wolgoweb文件，没有可供修改或者删除的地方。

**Comment by xiaoxinpro** [comment]
Web页面内容在源代码[/src/main.go](https://github.com/xiaoxinpro/WolGoWeb/blob/be4ed55d7fe7839dca7104e6c811d16da630e364/src/main.go#L92)文件内。

目前可以使用最新版本docker镜像[chishin/wol-go-web:dev](https://hub.docker.com/r/chishin/wol-go-web/tags)，修改环境变量`WEB`为`false`关闭Web页面。
