### ISSUE TITLE
请问支持R2S之类的ARM设备吗

### ISSUE THREAD

**Issue by MapleRedbean** [xiaoxinpro/WolGoWeb#17]

**Comment by xiaoxinpro** [comment]
支持

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月20日 09:33 |
| 收件人 | xiaoxinpro/WolGoWeb ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [xiaoxinpro/WolGoWeb] 请问支持R2S之类的ARM设备吗 (Issue #17) |
