### ISSUE TITLE
使API提供一个时间戳?

### ISSUE THREAD

**Issue by Xarth-Mai** [xiaoxinpro/WolGoWeb#20]
在iOS捷径中，访问启用了Token验证的实例时，需要一个时间戳，但捷径本身并未提供这个功能。如果能够添加一个API，通过WEB向客户端提供一个时间戳，将会非常有帮助。

**Comment by xiaoxinpro** [comment]
**iOS捷径中是有获取时间戳的方法，使用**`获取日期之间的时长`

![image](https://github.com/xiaoxinpro/WolGoWeb/assets/11443745/9193eabc-6211-4f04-b35a-e5e1f3b02229)

**具体创建方法参考：**

![image](https://github.com/xiaoxinpro/WolGoWeb/assets/11443745/a344ea1b-5289-44a6-966f-4af4a548e419)
