### ISSUE TITLE
请问在使用了Web页面登陆密码和账号以及API权限验证KEY的时候，如何设置快捷指令呢？

### ISSUE THREAD

**Issue by NikoYomi** [xiaoxinpro/WolGoWeb#24]
请问在使用了Web页面登陆密码和账号以及API权限验证KEY的时候，如何设置快捷指令呢？

**Comment by xiaoxinpro** [comment]
1. 设置 **Web页面登陆账号和密码** 并不影响API的执行。
2. 参考 [API权限验证](https://github.com/xiaoxinpro/WolGoWeb#4api%E6%9D%83%E9%99%90%E9%AA%8C%E8%AF%81)，你需要在快捷指令中获取时间戳并按照文档说明的结构组成token，最后将`token`和`time`与`mac`作为参数发送请求就可以了。

**Comment by NikoYomi** [comment]
> 1. 设置 **Web页面登陆账号和密码** 并不影响API的执行。
> 2. 参考 [API权限验证](https://github.com/xiaoxinpro/WolGoWeb#4api%E6%9D%83%E9%99%90%E9%AA%8C%E8%AF%81)，你需要在快捷指令中获取时间戳并按照文档说明的结构组成token，最后将`token`和`time`与`mac`作为参数发送请求就可以了。

感谢解答，我看的这个time我不太理解，是不是动态的？是请求时的time吧？如果是这样是不是无法使用快捷指令唤醒？

**Comment by xiaoxinpro** [comment]
time是当前时间戳，属于动态的，快捷指令中有个`获取日期之间的时长`，可以用于获取时间戳使用。

**Comment by xiaoxinpro** [comment]
参考 https://github.com/xiaoxinpro/WolGoWeb/issues/20#issuecomment-2002210153
