### ISSUE TITLE
关于istoeros的唤醒

### ISSUE THREAD

**Issue by NikoYomi** [xiaoxinpro/WolGoWeb#25]
istoreos主路由，下面分别是群晖和电脑。
在istores和群晖都安装了此项目，群晖能唤醒电脑，而istoresos无法唤醒电脑，这可能是什么问题呢？

**Comment by xiaoxinpro** [comment]
试试指定广播IP，如果还是不行就是系统的问题了。

**Comment by NikoYomi** [comment]
> 试试指定广播IP，如果还是不行就是系统的问题了。

怎么广播指定ip呢？我用的快捷指令，需要添加什么参数？

**Comment by NikoYomi** [comment]
> 试试指定广播IP，如果还是不行就是系统的问题了。

我这样子访问对吗？
http://ip:1234/wol?mac=Mac地址&ip=内网ip地址

**Comment by xiaoxinpro** [comment]
> 我这样子访问对吗？ [http://ip:1234/wol?mac=Mac地址&ip=内网ip地址](http://ip:1234/wol?mac=Mac%E5%9C%B0%E5%9D%80&ip=%E5%86%85%E7%BD%91ip%E5%9C%B0%E5%9D%80)

是的

**Comment by NikoYomi** [comment]
> > 我这样子访问对吗？ [http://ip:1234/wol?mac=Mac地址&ip=内网ip地址](http://ip:1234/wol?mac=Mac%E5%9C%B0%E5%9D%80&ip=%E5%86%85%E7%BD%91ip%E5%9C%B0%E5%9D%80)
> 
> 是的

页面显示成功，但是唤醒失败😭
