### ISSUE TITLE
电脑有开机密码该怎么处理？

### ISSUE THREAD

**Issue by noxchen** [xiaoxinpro/WolGoWeb#26]
大佬，请问电脑有开机密码该怎么处理？看了sakurafrp好像支持幻包中有密码。

**Comment by xiaoxinpro** [comment]
WOL是网卡功能，开机密码是操作系统层面的，无法实现WOL携带开机密码。
sakurafrp中携带密码应该是frp的隧道密码，我没有用过你可以试一下。

**Comment by noxchen** [comment]
好的，感谢
