### ISSUE TITLE
跨网段唤醒

### ISSUE THREAD

**Issue by wsczx** [xiaoxinpro/WolGoWeb#27]
作者您好，请问该项目支持跨网段唤醒吗？

**Comment by xiaoxinpro** [comment]
跨网段 WoL 的要求
- 路由器支持：您的路由器必须支持跨网段唤醒。
- 网络设置：目标计算机和发送“魔术包”的设备必须位于同一广播域中。
- 防火墙设置：两端的防火墙必须允许 UDP 端口 9 传输（用于 WoL）。
