### ISSUE TITLE
network参数不生效?

### ISSUE THREAD

**Issue by ubitsp** [xiaoxinpro/WolGoWeb#28]
部署在openwrt中使用 wol?network=eth2&mac=11-22-33-44-55-66  不能用

**Comment by xiaoxinpro** [comment]
你用的哪个镜像？目前`network`还在测试阶段，需要使用`dev`标签的镜像：

```
chishin/wol-go-web:dev
```

**Comment by ubitsp** [comment]
刚刚我直接编译了最新源码, 运行的时候提示 Network Interface Names: ["lo" "eth0" "wlan0" "wlan1" "br-lan" "eth0.1000" "eth0.30"] 但是只有eth0.30和br-lan可用,其他都提示route ip+net: no such network interface  , br-lan中的网络用Wireshark抓包也没收到魔术包

**Comment by xiaoxinpro** [comment]
你可以看一下终端输出的信息，启动时，会输出 `Network Interface Names: ...` 可用的网卡信息。
`br-lan` 应该时虚拟网桥，不会发出数据的。

**Comment by ubitsp** [comment]
确实不用桥接就行了
