### ISSUE TITLE
在我这里无法唤醒

### ISSUE THREAD

**Issue by jichengwei001** [xiaoxinpro/WolGoWeb#3]
我的电脑使用etherwake 是可以唤醒的，不知道这是为什么。
您需要我提供一些信息来帮助解决问题吗？

**Comment by xiaoxinpro** [comment]
你是用的docker还是服务器直接部署？先提供一下你的部署情况吧

无论如何你必须保证程序所在的局域网IP必须和你唤醒机器在一个网段里面，否则是无法唤醒的
