### ISSUE TITLE
openwrt x86+docker,系统进程中只有ipv6端口，没有ipv4的，无法唤醒电脑

### ISSUE THREAD

**Issue by tudoubocai** [xiaoxinpro/WolGoWeb#4]
如题！
在openwrt中安装wol插件可以唤醒局域网内的电脑，为了避免冲突，我尝试删除openwrt中的wol插件，但还是不行。
使用lsof - i:9090命令，显示wolgoweb只运行在ipv6上。
另，有计划编译openwrt直接安装的插件吗？
谢谢👍

**Comment by xiaoxinpro** [comment]
你要先确定你的docker是否开启了ipv4监听，然后查询容器的状态。
程序上是同时监听IPV4和IPV6的，你这个问题应该出在Docker上面。
另，不了解openwrt，开源代码中有二进制文件，可自行集成。

**Comment by tudoubocai** [comment]
> 
经过两天的测试，发现只能在局域网其它机器上安装wolgoweb才能唤醒别的电脑，哪怕是运行在路由器的docker里，用macvlan模式获取到非路由器ip就能唤醒……大概是openwrt没设置对。谢谢作者！
