### ISSUE TITLE
请求增加etherwake功能

### ISSUE THREAD

**Issue by missing233** [xiaoxinpro/WolGoWeb#5]
RT
主板不支持WOL，仅支持etherwake唤醒

**Comment by xiaoxinpro** [comment]
WOL和etherwake区别在于添加了指定IP地址，理论上目前版本是支持etherwake的，你可以试一下。

**Comment by missing233** [comment]
> WOL和etherwake区别在于添加了指定IP地址，理论上目前版本是支持etherwake的，你可以试一下。

不能生效。openwrt的wol功能也不行，但是执行"etherwake MAC地址"这个指令是可以的
